package com.w3villa.main.authentication.domain;

// Generated 1 Sep, 2012 6:48:24 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AlbumChoice generated by hbm2java
 */
@Entity
@Table(name = "album_choice", catalog = "w3villdb")
public class AlbumChoice implements java.io.Serializable {

	private Integer albumChoiceId;
	private String name;
	private String description;
	private Integer noOfPages;
	private Set<UserAlbumChoiceMpg> userAlbumChoiceMpgs = new HashSet<UserAlbumChoiceMpg>(
			0);

	public AlbumChoice() {
	}

	public AlbumChoice(String name, String description,
			Set<UserAlbumChoiceMpg> userAlbumChoiceMpgs, Integer noOfPages) {
		this.name = name;
		this.description = description;
		this.userAlbumChoiceMpgs = userAlbumChoiceMpgs;
		this.noOfPages = noOfPages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ALBUM_CHOICE_ID", unique = true, nullable = false)
	public Integer getAlbumChoiceId() {
		return this.albumChoiceId;
	}

	public void setAlbumChoiceId(Integer albumChoiceId) {
		this.albumChoiceId = albumChoiceId;
	}

	@Column(name = "NAME", length = 2000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "albumChoice", cascade = CascadeType.ALL)
	public Set<UserAlbumChoiceMpg> getUserAlbumChoiceMpgs() {
		return this.userAlbumChoiceMpgs;
	}

	public void setUserAlbumChoiceMpgs(
			Set<UserAlbumChoiceMpg> userAlbumChoiceMpgs) {
		this.userAlbumChoiceMpgs = userAlbumChoiceMpgs;
	}

	@Column(name = "NO_OF_PAGES")
	public Integer getNoOfPages() {
		return noOfPages;
	}

	public void setNoOfPages(Integer noOfPages) {
		this.noOfPages = noOfPages;
	}

}
