package com.w3villa.main.authentication.domain;

// Generated 11 Sep, 2012 12:18:17 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImageAlbumChoiceMapping generated by hbm2java
 */
@Entity
@Table(name = "image_album_choice_mapping", catalog = "w3villdb")
public class ImageAlbumChoiceMapping implements java.io.Serializable {

	private Integer imageAlbumChoiceMappingId;
	private ImageMapping imageMapping;
	private UserAlbumChoiceMpg userAlbumChoiceMpg;
	private Integer sequenceNo;

	public ImageAlbumChoiceMapping() {
	}

	public ImageAlbumChoiceMapping(ImageMapping imageMapping,
			UserAlbumChoiceMpg userAlbumChoiceMpg) {
		this.imageMapping = imageMapping;
		this.userAlbumChoiceMpg = userAlbumChoiceMpg;
	}

	public ImageAlbumChoiceMapping(ImageMapping imageMapping,
			UserAlbumChoiceMpg userAlbumChoiceMpg, Integer sequenceNo) {
		this.imageMapping = imageMapping;
		this.userAlbumChoiceMpg = userAlbumChoiceMpg;
		this.sequenceNo = sequenceNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "image_album_choice_mapping_id", unique = true, nullable = false)
	public Integer getImageAlbumChoiceMappingId() {
		return this.imageAlbumChoiceMappingId;
	}

	public void setImageAlbumChoiceMappingId(Integer imageAlbumChoiceMappingId) {
		this.imageAlbumChoiceMappingId = imageAlbumChoiceMappingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "image_mapping_id", nullable = false)
	public ImageMapping getImageMapping() {
		return this.imageMapping;
	}

	public void setImageMapping(ImageMapping imageMapping) {
		this.imageMapping = imageMapping;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ALBUM_CHOICE_MPG_ID", nullable = false)
	public UserAlbumChoiceMpg getUserAlbumChoiceMpg() {
		return this.userAlbumChoiceMpg;
	}

	public void setUserAlbumChoiceMpg(UserAlbumChoiceMpg userAlbumChoiceMpg) {
		this.userAlbumChoiceMpg = userAlbumChoiceMpg;
	}

	@Column(name = "sequence_no")
	public Integer getSequenceNo() {
		return this.sequenceNo;
	}

	public void setSequenceNo(Integer sequenceNo) {
		this.sequenceNo = sequenceNo;
	}

}
