package com.w3villa.main.authentication.domain;

// Generated 26 Aug, 2012 11:19:59 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImageMapping generated by hbm2java
 */
@Entity
@Table(name = "image_mapping", catalog = "w3villdb")
public class ImageMapping implements java.io.Serializable {

	private Integer imageMappingId;
	private Users users;
	private String imagePath;

	public ImageMapping() {
	}

	public ImageMapping(Users users) {
		this.users = users;
	}

	public ImageMapping(Users users, String imagePath) {
		this.users = users;
		this.imagePath = imagePath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "image_mapping_id", unique = true, nullable = false)
	public Integer getImageMappingId() {
		return this.imageMappingId;
	}

	public void setImageMappingId(Integer imageMappingId) {
		this.imageMappingId = imageMappingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "image_path", length = 2000)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

}
