package com.w3villa.main.authentication.domain;

// Generated 9 Jul, 2012 2:47:13 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StylePreference generated by hbm2java
 */
@Entity
@Table(name = "style_preference", catalog = "w3villdb")
public class StylePreference implements java.io.Serializable {

	private Integer stylePreferenceId;
	private String name;
	private String description;
	private Set<UserStylePreferncesMpg> userStylePreferncesMpgs = new HashSet<UserStylePreferncesMpg>(
			0);

	public StylePreference() {
	}

	public StylePreference(String name, String description,
			Set<UserStylePreferncesMpg> userStylePreferncesMpgs) {
		this.name = name;
		this.description = description;
		this.userStylePreferncesMpgs = userStylePreferncesMpgs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "STYLE_PREFERENCE_ID", unique = true, nullable = false)
	public Integer getStylePreferenceId() {
		return this.stylePreferenceId;
	}

	public void setStylePreferenceId(Integer stylePreferenceId) {
		this.stylePreferenceId = stylePreferenceId;
	}

	@Column(name = "NAME", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stylePreference")
	public Set<UserStylePreferncesMpg> getUserStylePreferncesMpgs() {
		return this.userStylePreferncesMpgs;
	}

	public void setUserStylePreferncesMpgs(
			Set<UserStylePreferncesMpg> userStylePreferncesMpgs) {
		this.userStylePreferncesMpgs = userStylePreferncesMpgs;
	}

	@Override
	public String toString() {
		return "StylePreference [stylePreferenceId=" + stylePreferenceId
				+ ", name=" + name + ", description=" + description + "]";
	}

}
