package com.w3villa.main.authentication.domain;

// Generated 21 Jun, 2012 12:37:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "w3villdb")
public class Users implements java.io.Serializable {

	private int userId;
	private String firstName;
	private String password;
	private String isActive;
	private String lastName;
	private String emailId;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String state;
	private String country;
	private String contactNo;
	private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);

	public Users() {
	}

	public Users(int userId, String firstName, String password,
			String isActive, String lastName, String emailId) {
		this.userId = userId;
		this.firstName = firstName;
		this.password = password;
		this.isActive = isActive;
		this.lastName = lastName;
		this.emailId = emailId;
	}

	public Users(int userId, String firstName, String password,
			String isActive, String lastName, String emailId,
			String addressLine1, String addressLine2, String city,
			String state, String country, String contactNo, Set<UserRoles> userRoleses) {
		this.userId = userId;
		this.firstName = firstName;
		this.password = password;
		this.isActive = isActive;
		this.lastName = lastName;
		this.emailId = emailId;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.state = state;
		this.country = country;
		this.contactNo = contactNo;
		this.userRoleses = userRoleses;
	}

	@Id
	@Column(name = "USER_ID", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "FIRST_NAME", nullable = false, length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "PASSWORD", nullable = false, length = 2000)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "IS_ACTIVE", nullable = false, length = 1)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EMAIL_ID", nullable = false, length = 200)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "ADDRESS_LINE_1", length = 1000)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "ADDRESS_LINE_2", length = 1000)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "CITY", length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "COUNTRY", length = 100)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "CONTACT_NO", length = 15)
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserRoles> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRoles> userRoleses) {
		this.userRoleses = userRoleses;
	}

	@Override
	public String toString() {
		return "Users [userId=" + userId + ", firstName=" + firstName
				+ ", password=" + password + ", isActive=" + isActive
				+ ", lastName=" + lastName + ", emailId=" + emailId
				+ ", addressLine1=" + addressLine1 + ", addressLine2="
				+ addressLine2 + ", city=" + city + ", state=" + state
				+ ", country=" + country + ", contactNo=" + contactNo + "]\n";
	}

	
	
	

}
