package com.w3villa.main.authentication.domain;

// Generated 9 Jul, 2012 2:47:13 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserStylePreferncesMpg generated by hbm2java
 */
@Entity
@Table(name = "user_style_prefernces_mpg", catalog = "w3villdb")
public class UserStylePreferncesMpg implements java.io.Serializable {

	private int userStylePreferncesMpgId;
	private Users users;
	private StylePreference stylePreference;

	public UserStylePreferncesMpg() {
	}

	public UserStylePreferncesMpg(int userStylePreferncesMpgId, Users users,
			StylePreference stylePreference) {
		this.userStylePreferncesMpgId = userStylePreferncesMpgId;
		this.users = users;
		this.stylePreference = stylePreference;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_STYLE_PREFERNCES_MPG_ID", unique = true, nullable = false)
	public int getUserStylePreferncesMpgId() {
		return this.userStylePreferncesMpgId;
	}

	public void setUserStylePreferncesMpgId(int userStylePreferncesMpgId) {
		this.userStylePreferncesMpgId = userStylePreferncesMpgId;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "USER_ID", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "STYLE_PREFERENCE_ID", nullable = false)
	public StylePreference getStylePreference() {
		return this.stylePreference;
	}

	public void setStylePreference(StylePreference stylePreference) {
		this.stylePreference = stylePreference;
	}

}
